import { Activity, Ambulance, BadgeCheck, BellRing, Building2, CloudSun, LogOut, Menu, Search, ShieldAlert, Sparkles, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import Sidebar from '../components/Sidebar'
import CityMap from '../components/CityMap'
import LayerControl from '../components/LayerControl'
import SimulationModal from '../components/SimulationModal'
import { cityService } from '../services/cityService'

const icons = { BellRing, BadgeCheck, ShieldAlert, Ambulance, CloudSun, Hospital: Building2, Users: Activity }
const emptyOverview = { verified_reports: 0, active_alerts: 0, available_ambulances: 0, latest_aqi: null, environment: null }
const relativeTime = (time) => time ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(time)) : '—'

export default function DashboardPage() {
  const [layers, setLayers] = useState({ rainfall: false, aqi: false, temperature: false, traffic: false, pandemic: false, waterlogging: false, issues: true, hospitals: false, ambulances: false })
  const [target, setTarget] = useState(null)
  const [modal, setModal] = useState(false)
  const [search, setSearch] = useState('')
  const [overview, setOverview] = useState(emptyOverview)
  const [alerts, setAlerts] = useState([])
  const [reports, setReports] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => { let active = true; Promise.all([cityService.overview(), cityService.alerts(), cityService.reports()]).then(([overviewResponse, alertResponse, reportResponse]) => { if (!active) return; setOverview(overviewResponse.data); setAlerts(alertResponse.data.alerts || []); setReports(reportResponse.data.reports || []) }).catch((requestError) => { if (active) setError(requestError.response?.data?.error || 'Live city data is currently unavailable.') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [])

  const searched = useMemo(() => reports.find((report) => report.title.toLowerCase().includes(search.toLowerCase())), [reports, search])
  const stats = [['Active alerts', overview.active_alerts, 'BellRing'], ['Verified reports', overview.verified_reports, 'BadgeCheck'], ['Available ambulances', overview.available_ambulances, 'Ambulance'], ['Latest AQI', overview.latest_aqi ?? 'No data', 'ShieldAlert'], ['Rainfall (1h)', `${overview.environment?.rainfall_mm ?? 0} mm`, 'CloudSun'], ['Temperature', overview.environment?.temperature_c === null || overview.environment?.temperature_c === undefined ? 'No data' : `${overview.environment.temperature_c} °C`, 'CloudSun']]
  const signOut = () => { sessionStorage.removeItem('citytwin_token'); sessionStorage.removeItem('citytwin_admin'); window.location.assign('/login') }

  return <div className="flex min-h-screen bg-[#eaf7f8]"><Sidebar onSimulation={() => setModal(true)}/><main className="min-w-0 flex-1 p-4 md:p-6"><header className="mb-5 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><button className="rounded-xl bg-white p-2 lg:hidden"><Menu size={20}/></button><div><p className="hidden text-xs font-medium uppercase tracking-[.16em] text-[#6a9c98] sm:block">Live database view</p><h1 className="text-xl font-bold tracking-tight sm:text-2xl">Central Command Center</h1></div></div><div className="flex items-center gap-2 sm:gap-3"><div className="hidden items-center gap-2 rounded-full bg-white px-3 py-2 text-xs font-semibold text-[#41877f] md:flex"><span className="h-2 w-2 rounded-full bg-[#6fc4bc]"/>Connected</div><button onClick={signOut} title="Sign out" className="rounded-xl bg-white p-2.5 text-[#65717a]"><LogOut size={19}/></button></div></header>{error && <p className="mb-5 rounded-xl bg-[#fff1f0] px-4 py-3 text-sm text-[#a84d48]">{error}</p>}
<section className="mb-5 grid grid-cols-2 gap-3 md:grid-cols-4">{stats.map(([label, value, icon]) => { const Icon = icons[icon]; return <article key={label} className="rounded-2xl border border-white/80 bg-white px-4 py-3.5 shadow-card"><div className="flex items-center justify-between"><span className="text-xs text-[#737783]">{label}</span><Icon size={16} className="text-[#6aa8a2]"/></div><p className="mt-2 text-xl font-bold">{loading ? '—' : value}</p></article> })}</section>
<div className="grid gap-5 2xl:grid-cols-[minmax(0,1fr)_340px]"><section className="min-w-0"><div className="relative h-[520px] overflow-hidden rounded-[24px] border border-white bg-[#e8eeee] shadow-card md:h-[calc(100vh-242px)]"><CityMap layers={layers} target={target} reports={reports}/><LayerControl layers={layers} setLayers={setLayers}/><div className="absolute right-5 top-5 z-[500] flex w-52 items-center rounded-xl bg-white/95 px-3 py-2.5 shadow-card"><Search size={16} className="mr-2 text-[#71908e]"/><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && searched?.location && setTarget(null)} placeholder="Search reports" className="min-w-0 bg-transparent text-sm outline-none placeholder:text-[#9ca7aa]"/>{search && <button onClick={() => setSearch('')}><X size={14}/></button>}</div><div className="absolute bottom-5 left-5 z-[500] rounded-xl bg-white/95 px-3 py-2 text-xs text-[#667177] shadow-card">{reports.length ? `${reports.length} verified report${reports.length === 1 ? '' : 's'} on this view` : 'No report locations to display'}</div></div></section><aside className="space-y-5"><section className="rounded-[22px] border border-white bg-white p-5 shadow-card"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-semibold tracking-[.14em] text-[#5b9690]">CITY INTELLIGENCE</p><h2 className="mt-1 font-bold">Operational signals</h2></div><CloudSun className="text-[#6fc4bc]"/></div><div className="rounded-xl bg-[#f7fbfb] p-3 text-sm text-[#737783]">{overview.latest_aqi === null ? 'No environmental readings have been recorded yet.' : `Latest recorded AQI: ${overview.latest_aqi}`}</div></section><section className="rounded-[22px] border border-white bg-white p-5 shadow-card"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold">City alerts</h2><BellRing size={18} className="text-[#6fc4bc]"/></div>{alerts.length ? <div className="space-y-1">{alerts.map((alert) => <article key={alert.id} className="flex w-full items-center gap-3 rounded-xl p-2"><span className="h-2.5 w-2.5 shrink-0 rounded-full bg-[#e8b06f]"/><div className="min-w-0 flex-1"><p className="text-sm font-medium">{alert.title}</p><p className="truncate text-xs text-[#737783]">{alert.message || alert.alert_type}</p></div><span className="text-[11px] text-[#919aa3]">{relativeTime(alert.created_at)}</span></article>)}</div> : <p className="py-5 text-center text-sm text-[#858c95]">No alerts yet.</p>}</section></aside></div>
<section className="mt-5 rounded-[22px] border border-white bg-white p-5 shadow-card"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-semibold tracking-[.14em] text-[#5b9690]">GENAI-ASSISTED FILTER</p><h2 className="mt-1 font-bold">Verified citizen reports</h2></div><Activity size={18} className="text-[#6fc4bc]"/></div>{reports.length ? <div className="grid gap-2 md:grid-cols-3">{reports.map((report) => <article key={report.id} className="rounded-xl border border-[#edf2f2] p-3"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-semibold text-[#5b9690]">{report.category?.name || 'Report'}</span><span className="rounded-full bg-[#e8f7f2] px-2 py-1 text-[10px] font-bold text-[#41877f]">Verified</span></div><p className="font-medium">{report.title}</p><p className="mt-1 text-xs text-[#737783]">{relativeTime(report.created_at)}</p></article>)}</div> : <p className="rounded-xl bg-[#f7fbfb] py-8 text-center text-sm text-[#858c95]">No verified citizen reports yet.</p>}<p className="mt-3 text-xs text-[#858c95]">Verification is a review aid; uncertain reports require administrator assessment.</p></section>
<button onClick={() => setModal(true)} className="fixed bottom-5 right-5 z-[600] flex items-center gap-2 rounded-2xl bg-[#397b76] px-5 py-3.5 text-sm font-semibold text-white shadow-xl shadow-[#397b76]/25"><Sparkles size={18}/>AI Simulation</button>{modal && <SimulationModal close={() => setModal(false)}/>}</main></div>
}
